name: expense_tracker_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  user_repository:
    path: packages/user_repository

  expense_repository:
   path: packages/expense_repository
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^5.1.0
  image_picker: ^1.1.2
  image_cropper: ^7.0.5
  syncfusion_flutter_charts: ^26.1.39
  google_sign_in: ^6.2.1
  firebase_app_check: ^0.3.0+1
  flutter_slidable: ^3.1.0
  pinput: ^5.0.0
  shared_preferences: ^2.2.3
  local_auth: ^2.2.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - icon/


flutter_icons:
  android: true
  ios: true
  image_path: "icon/icon.jpg"