name: expense_repository
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  user_repository:
    path: ../user_repository

  

firebase_auth:
# cloud_firestore:
# firebase_storage:
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
