// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnGBJQ4HWubmz790-WLkoc1ESbt1d-qjU',
    appId: '1:158423296854:web:218055bc18dbf4ce7384f7',
    messagingSenderId: '158423296854',
    projectId: 'expense-tracker-app-6cc99',
    authDomain: 'expense-tracker-app-6cc99.firebaseapp.com',
    storageBucket: 'expense-tracker-app-6cc99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3glMjhPdThKKR7jWJkT-vTjkkgQf58uc',
    appId: '1:158423296854:android:6349c9ac099154a17384f7',
    messagingSenderId: '158423296854',
    projectId: 'expense-tracker-app-6cc99',
    storageBucket: 'expense-tracker-app-6cc99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzDdN_g22aqJCuEK7xuCWUXzqlXarp6yA',
    appId: '1:158423296854:ios:b67b0200d57b59bc7384f7',
    messagingSenderId: '158423296854',
    projectId: 'expense-tracker-app-6cc99',
    storageBucket: 'expense-tracker-app-6cc99.appspot.com',
    iosBundleId: 'com.example.expenseTrackerProject',
  );
}
